# networks:
#   custom:
#     ipam:
#       config:
#         - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin24!!
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    # networks:
    #   custom:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db
    # networks:
    #   custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    # networks:
    #   custom:
  auction-svc:
    image: wkumanuvong/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;User Id=postgres;Password=admin24!!;Database=auctions;Pooling=true
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
    # networks:
    #   custom:
  search-svc:
    image: wkumanuvong/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    # networks:
    #   custom:
  identity-svc:
    image: wkumanuvong/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IssuerUri=https://id.carauction.local
      - ClientApp=https://app.carauction.local
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;User Id=postgres;Password=admin24!!;Database=identity;Pooling=true
      - VIRTUAL_HOST=id.carauction.local
    depends_on:
      - postgres
    # networks:
    #   custom:
    #     ipv4_address: 10.5.0.200
  gateway-svc:
    image: wkumanuvong/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carauction.local
      - VIRTUAL_HOST=api.carauction.local
    # networks:
    #   custom:
  bid-svc:
    image: wkumanuvong/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
    # networks:
    #   custom:
  notify-svc:
    image: wkumanuvong/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
    # networks:
    #   custom:
  web-app:
    image: wkumanuvong/web-app
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    # extra_hosts:
    #   - id.carauction.com:10.5.0.200
    environment:
      - AUTH_SECRET="OBuZoHo4m4Dss4+1gGswbHpH1kU+AbzRcy9/PF1VGV0="
      - AUTH_URL=https://app.carauction.local
      - AUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=https://id.carauction.local
      - ID_URL_INTERNAL=http://identity-svc
      - NOTIFY_URL=https://api.carauction.local/notifications
      - VIRTUAL_HOST=app.carauction.local
      - VIRTUAL_PORT=3000
      #   networks:
      #     custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
  #   networks:
  #     custom:

